name: Test project
on: 
  push
jobs:
  test:
    runs_on: ubuntu-latest
    steps:
      - name: Get code 
        uses: actions/checkout@v3
        # Install dependencies and build the app.
      - name: Install nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        uses: npm ci
      - name: Run tests
        run: npm test
